name: Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v0.1.0)'
        required: true

permissions:
  contents: write

jobs:
  prebuilt:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux musl amd64
          - os: ubuntu-latest
            target: linux_amd64_musl
            cc: x86_64-linux-musl-gcc
            cxx: x86_64-linux-musl-g++
            ar:  x86_64-linux-musl-ar
            ranlib: x86_64-linux-musl-ranlib
          # macOS Intel
          - os: macos-13
            target: darwin_amd64
            cc: clang
            cxx: clang++
            ar:  ar
            ranlib: ranlib
          # macOS Apple Silicon
          - os: macos-14
            target: darwin_arm64
            cc: clang
            cxx: clang++
            ar:  ar
            ranlib: ranlib
          # (Windows désactivé ici)

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-go@v5
        with: { go-version: '1.22.x' }

      - name: Install deps (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git upx musl-tools pkg-config autoconf automake libtool

      - name: Show toolchains
        shell: bash
        run: |
          echo "go: $(go version)"
          echo "CC:  ${{ matrix.cc }}"
          echo "CXX: ${{ matrix.cxx }}"
          command -v ${{ matrix.cc }} || true
          command -v ${{ matrix.cxx }} || true

      - name: Build & package prebuilt
        shell: bash
        env:
          # Utiliser musl partout (Linux) ; clang sur macOS
          CC:      ${{ matrix.cc }}
          CXX:     ${{ matrix.cxx }}
          AR:      ${{ matrix.ar }}
          RANLIB:  ${{ matrix.ranlib }}
          # Variables lues par ton Makefile
          MUSL_CC: ${{ matrix.cc }}
          TARGET:  ${{ matrix.target }}
          # Nettoie des flags auto ajoutés par configure si besoin
          CFLAGS: ""
          CXXFLAGS: ""
          LDFLAGS: ""
        run: |
          set -euxo pipefail
          make package TARGET="${TARGET}"
          echo "Contents:"
          find "v1/prebuilt/${TARGET}" -maxdepth 2 -type f -print
          tar -C v1 -czf "prebuilt-${TARGET}.tar.gz" "prebuilt/${TARGET}"

      - name: Determine release tag
        id: tag
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "name=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi
          echo "Release tag: $(cat $GITHUB_OUTPUT)"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.name }}
          files: prebuilt-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
